### ISSUE TITLE
Find yamllint config at a given path

### ISSUE THREAD

**Issue by warren-vodafone** [ferhaty/linter-yaml#9]
Great plugin, but I've no idea how to use it - Yet.
Also all my lint configs are at relative to the ${GITROOT}/.github/.yaml-lint-conf.yaml - I don't know how to express this.

**Comment by ferhaty** [comment]
By default it uses a .yamllint file in your project folder. 

For example:

```yaml
---

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
  comments-indentation:
    level: warning
  document-end: disable
  document-start:
    level: warning
  empty-lines: enable
  empty-values: disable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  line-length: enable
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
```
